In [3]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
a.shape
a.ndim
a.size
a.dtype.name
a.itemsize

4

### Array creation

In [18]:
a = np.array([1, 2, 3])
print(a.shape, a, a.dtype.name, a.size)
b = np.array([[1, 2, 4], [1, 2, 3], [2,3,4]], dtype=complex)
print(b, b.shape, b.dtype.name, b.size)

(3,) [1 2 3] int32 3
[[1.+0.j 2.+0.j 4.+0.j]
 [1.+0.j 2.+0.j 3.+0.j]
 [2.+0.j 3.+0.j 4.+0.j]] (3, 3) complex128 9


In [22]:
a = np.zeros((3, 4))
b = np.ones((2, 3, 4), dtype='int64')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [32]:
a = np.arange(10, 20,1, dtype='float64')
print(a)
a = np.linspace(0, 30, 100)
print(a)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[ 0.          0.3030303   0.60606061  0.90909091  1.21212121  1.51515152
  1.81818182  2.12121212  2.42424242  2.72727273  3.03030303  3.33333333
  3.63636364  3.93939394  4.24242424  4.54545455  4.84848485  5.15151515
  5.45454545  5.75757576  6.06060606  6.36363636  6.66666667  6.96969697
  7.27272727  7.57575758  7.87878788  8.18181818  8.48484848  8.78787879
  9.09090909  9.39393939  9.6969697  10.         10.3030303  10.60606061
 10.90909091 11.21212121 11.51515152 11.81818182 12.12121212 12.42424242
 12.72727273 13.03030303 13.33333333 13.63636364 13.93939394 14.24242424
 14.54545455 14.84848485 15.15151515 15.45454545 15.75757576 16.06060606
 16.36363636 16.66666667 16.96969697 17.27272727 17.57575758 17.87878788
 18.18181818 18.48484848 18.78787879 19.09090909 19.39393939 19.6969697
 20.         20.3030303  20.60606061 20.90909091 21.21212121 21.51515152
 21.81818182 22.12121212 22.42424242 22.72727273 23.03030303 23.33333333
 23.636363

### Basic Operations

In [53]:
a = np.array([0, 10, 20, 30, 40, 50]).reshape(3, 2)
b = np.arange(a.size).reshape(a.shape[0], a.shape[1])
c = a-b
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [65]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(5)
c = a-b
d = b**2
print(c, d)
e = np.linspace(0, np.pi/2, 5)
print(e, np.sin(e))
a<35


[10 19 28 37 46] [ 0  1  4  9 16]
[0.         0.39269908 0.78539816 1.17809725 1.57079633] [0.         0.38268343 0.70710678 0.92387953 1.        ]


array([ True,  True,  True, False, False])

In [78]:
A = np.arange(0, 40, 10).reshape(2,2)
B = np.arange(0, 80, 20).reshape(2,2)
print(A)
print(B)
print(A*B)
print(A @ B)
print(A.dot(B))
a = np.ones((2,3), dtype='int32')
b = np.random.randint(5,size=(2,3))
a*=3
print(a)
b += a
print(b)
a = np.ones(3, dtype='int32')
b = np.linspace(0, np.pi, 3)
c = a+b
print(c, c.dtype.name)
d = np.exp(c*1j)
print(d, d.dtype)

[[ 0 10]
 [20 30]]
[[ 0 20]
 [40 60]]
[[   0  200]
 [ 800 1800]]
[[ 400  600]
 [1200 2200]]
[[ 400  600]
 [1200 2200]]
[[3 3 3]
 [3 3 3]]
[[6 6 3]
 [3 3 3]]
[1.         2.57079633 4.14159265] float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j] complex128


In [80]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.4366842  0.53294007 0.33623722]
 [0.43722477 0.24546652 0.31315753]]
2.301710300636471
0.24546651705558808
0.5329400703082573


### Universal Functions

In [84]:
B = np.arange(3)
print(np.exp(B), np.sqrt(B), B)

[1.         2.71828183 7.3890561 ] [0.         1.         1.41421356] [0 1 2]


### Indexing, Slicing, and Iterating

In [106]:
a = np.arange(10)**3
print(a, a[2:5])
# a[0:-1:3] = -10
print(a)


[  0   1   8  27  64 125 216 343 512 729] [ 8 27 64]
[  0   1   8  27  64 125 216 343 512 729]


In [108]:
print(a[0:-1:2])

[  0   8  64 216 512]


In [116]:
def f(x, y):
    return 10*x+y
b = np.fromfunction(f, (5,4), dtype=int)
print(b)
print(b[:, 3])
print(b[:2, :])
print(b[-1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[ 3 13 23 33 43]
[[ 0  1  2  3]
 [10 11 12 13]]
[40 41 42 43]


### Shape Manipulation

In [127]:
a =  np.floor(10*np.random.random((3, 4)))
print(a)
a.ravel()
print('6x2',a.reshape(6,2))
print(a.T)

[[0. 9. 1. 4.]
 [3. 5. 3. 1.]
 [7. 2. 4. 4.]]
6x2 [[0. 9.]
 [1. 4.]
 [3. 5.]
 [3. 1.]
 [7. 2.]
 [4. 4.]]
[[0. 3. 7.]
 [9. 5. 2.]
 [1. 3. 4.]
 [4. 1. 4.]]


### Stacking Different Arrays

In [131]:
a = np.random.randint(10,size=(2,2))
b = np.random.randint(10,size=(2,2))
print(a, b)
np.vstack((a,b))
np.hstack((a, b))

[[1 7]
 [4 3]] [[2 6]
 [3 5]]


array([[1, 7, 2, 6],
       [4, 3, 3, 5]])

### Splitting one array into several smaller ones

In [138]:
a = np.random.randint(10,size=(3, 4))
c = a.view()
c is a
c.base is a
c.flags.owndata
print(a.shape)
c[1, 0] = 1234
print(a)

(3, 4)
[[   0    2    0    2]
 [1234    9    3    8]
 [   6    5    1    8]]


In [141]:
s = a[:, 1:3]
s[:] =10
print(s, a)

[[10 10]
 [10 10]
 [10 10]] [[   0   10   10    2]
 [1234   10   10    8]
 [   6   10   10    8]]
